package layout

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"math"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"sync"
	"time"

	"github.com/coxley/dg/ir"
)

const (
	historyCacheVersion = 1
	defaultCacheDelay   = 100 * time.Millisecond
)

// HistoryStore reads and atomically replaces path-keyed cache values.
type HistoryStore interface {
	Read(name string) ([]byte, error)
	Write(name string, data []byte) error
}

type directoryHistoryStore struct {
	dir string
}

func (s directoryHistoryStore) Read(name string) ([]byte, error) {
	return os.ReadFile(filepath.Join(s.dir, name)) //nolint:gosec // name is a SHA-256 digest generated by History.
}

func (s directoryHistoryStore) Write(name string, data []byte) error {
	if err := os.MkdirAll(s.dir, 0o700); err != nil {
		return fmt.Errorf("create history cache directory: %w", err)
	}
	file, err := os.CreateTemp(s.dir, ".history-*")
	if err != nil {
		return fmt.Errorf("create history cache temporary file: %w", err)
	}
	tempPath := file.Name()
	if err := file.Chmod(0o600); err != nil {
		return cleanupHistoryTemp(file, tempPath, fmt.Errorf("set history cache permissions: %w", err))
	}
	if _, err := file.Write(data); err != nil {
		return cleanupHistoryTemp(file, tempPath, fmt.Errorf("write history cache: %w", err))
	}
	if err := file.Close(); err != nil {
		return cleanupHistoryPath(tempPath, fmt.Errorf("close history cache: %w", err))
	}
	if err := os.Rename(tempPath, filepath.Join(s.dir, name)); err != nil {
		return cleanupHistoryPath(tempPath, fmt.Errorf("replace history cache: %w", err))
	}
	return nil
}

func cleanupHistoryTemp(file *os.File, path string, cause error) error {
	return errors.Join(cause, file.Close(), removeHistoryTemp(path))
}

func cleanupHistoryPath(path string, cause error) error {
	return errors.Join(cause, removeHistoryTemp(path))
}

func removeHistoryTemp(path string) error {
	err := os.Remove(path)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	return err
}

// WithHistoryCacheDir stores cache files directly in dir.
func WithHistoryCacheDir(dir string) HistoryOption {
	return func(h *History) {
		h.cacheDir = dir
		h.customCacheDir = true
	}
}

// WithHistoryStore replaces filesystem cache access.
func WithHistoryStore(store HistoryStore) HistoryOption {
	return func(h *History) {
		h.cacheStore = store
		h.customStore = true
	}
}

// WithHistoryCacheDelay changes the inactivity interval before cache writes.
func WithHistoryCacheDelay(delay time.Duration) HistoryOption {
	return func(h *History) {
		h.cacheDelay = delay
	}
}

// Store marks the current layout as saved at path and writes its history.
func (h *History) Store(path string) error {
	if h == nil || h.layout == nil {
		return errors.New("history is not attached")
	}
	h.Interrupt()
	if err := h.layout.Build(); err != nil {
		return err
	}
	normalized, key, err := historyCacheKey(path)
	if err != nil {
		return err
	}
	store, err := h.store()
	if err != nil {
		return err
	}

	h.cachePath = normalized
	h.cacheKey = key
	h.savedCursor = h.cursor
	h.savedState = h.layout.historyState()
	h.cacheBranchValid = true
	data, err := h.marshalCache()
	if err != nil {
		return err
	}
	h.cancelPendingCache()
	h.cacheMu.Lock()
	generation := h.cacheGeneration
	h.cacheMu.Unlock()
	err = h.writeCache(cacheWrite{
		generation: generation,
		store:      store,
		key:        key,
		data:       data,
	})
	h.setCacheError(err)
	return err
}

// Restore attaches cached history for path without changing its saved render.
func (h *History) Restore(path string) (bool, error) {
	if h == nil || h.layout == nil {
		return false, errors.New("history is not attached")
	}
	normalized, key, err := historyCacheKey(path)
	if err != nil {
		return false, err
	}
	store, err := h.store()
	if err != nil {
		return false, err
	}
	h.cancelPendingCache()
	h.cachePath = normalized
	h.cacheKey = key
	h.savedCursor = h.cursor
	h.savedState = h.layout.historyState()
	h.cacheBranchValid = true
	data, err := store.Read(key)
	if errors.Is(err, fs.ErrNotExist) {
		h.setCacheError(nil)
		return false, nil
	}
	if err != nil {
		err = fmt.Errorf("read history cache: %w", err)
		h.setCacheError(err)
		return false, err
	}
	cache, ok := decodeHistoryCache(data)
	if !ok {
		h.setCacheError(nil)
		return false, nil
	}
	currentDigest, err := semanticHistoryDigest(h.layout.historyState())
	if err != nil {
		return false, err
	}
	savedState, ok := cache.Saved.layoutState()
	if !ok || cache.SavedDigest != currentDigest {
		return false, nil
	}
	savedDigest, err := semanticHistoryDigest(savedState)
	if err != nil || savedDigest != cache.SavedDigest {
		return false, nil
	}
	entries, ok := cache.historyEntries()
	if !ok || cache.SavedCursor < 0 || cache.SavedCursor > len(entries) {
		return false, nil
	}

	rollback := h.layout.historyState()
	err = h.restoreLayoutState(savedState)
	if err != nil {
		restoreErr := h.restoreLayoutState(rollback)
		return false, errors.Join(err, restoreErr)
	}
	h.entries = entries
	h.cursor = cache.SavedCursor
	h.savedCursor = cache.SavedCursor
	cacheBranchValid := len(entries)-h.limit <= cache.SavedCursor
	h.enforceLimit()
	h.savedState = h.layout.historyState()
	h.cachePath = normalized
	h.cacheKey = key
	h.cacheBranchValid = cacheBranchValid
	h.closeActive()
	h.setCacheError(nil)
	return true, nil
}

// Flush synchronously writes the latest pending cache snapshot.
func (h *History) Flush() error {
	if h == nil {
		return nil
	}
	h.cacheMu.Lock()
	if h.cacheTimer != nil {
		h.cacheTimer.Stop()
	}
	pending := h.pendingCache
	h.pendingCache = cacheWrite{}
	h.cacheMu.Unlock()
	if pending.data == nil {
		return h.CacheError()
	}
	err := h.writeCache(pending)
	h.setCacheError(err)
	return err
}

// CacheError returns the most recent asynchronous cache error.
func (h *History) CacheError() error {
	if h == nil {
		return nil
	}
	h.cacheMu.Lock()
	defer h.cacheMu.Unlock()
	return h.cacheErr
}

func (h *History) scheduleCache() {
	if h.cachePath == "" || !h.cacheBranchValid {
		return
	}
	data, err := h.marshalCache()
	if err != nil {
		h.setCacheError(err)
		return
	}
	store, err := h.store()
	if err != nil {
		h.setCacheError(err)
		return
	}
	h.cacheMu.Lock()
	h.cacheGeneration++
	generation := h.cacheGeneration
	h.pendingCache = cacheWrite{
		generation: generation,
		store:      store,
		key:        h.cacheKey,
		data:       data,
	}
	if h.cacheTimer != nil {
		h.cacheTimer.Stop()
	}
	h.cacheTimer = time.AfterFunc(h.cacheDelay, func() {
		h.flushGeneration(generation)
	})
	h.cacheMu.Unlock()
}

func (h *History) flushGeneration(generation uint64) {
	h.cacheMu.Lock()
	if h.pendingCache.generation != generation {
		h.cacheMu.Unlock()
		return
	}
	pending := h.pendingCache
	h.pendingCache = cacheWrite{}
	h.cacheMu.Unlock()

	err := h.writeCache(pending)
	h.cacheMu.Lock()
	if h.cacheGeneration == generation {
		h.cacheErr = err
	}
	h.cacheMu.Unlock()
}

func (h *History) writeCache(write cacheWrite) error {
	h.cacheWriteMu.Lock()
	defer h.cacheWriteMu.Unlock()
	h.cacheMu.Lock()
	stale := write.generation != h.cacheGeneration
	h.cacheMu.Unlock()
	if stale {
		return nil
	}
	compressed, err := compressHistoryCache(write.data)
	if err != nil {
		return err
	}
	h.cacheMu.Lock()
	stale = write.generation != h.cacheGeneration
	h.cacheMu.Unlock()
	if stale {
		return nil
	}
	if err := write.store.Write(write.key, compressed); err != nil {
		return fmt.Errorf("write history cache: %w", err)
	}
	return nil
}

func (h *History) cancelPendingCache() {
	h.cacheMu.Lock()
	h.cacheGeneration++
	h.pendingCache = cacheWrite{}
	if h.cacheTimer != nil {
		h.cacheTimer.Stop()
	}
	h.cacheMu.Unlock()
}

func (h *History) setCacheError(err error) {
	h.cacheMu.Lock()
	h.cacheErr = err
	h.cacheMu.Unlock()
}

func (h *History) store() (HistoryStore, error) {
	if h.cacheStore != nil {
		return h.cacheStore, nil
	}
	dir := h.cacheDir
	if dir == "" {
		var err error
		dir, err = defaultHistoryCacheDir()
		if err != nil {
			return nil, err
		}
		h.cacheDir = dir
	}
	h.cacheStore = directoryHistoryStore{dir: dir}
	return h.cacheStore, nil
}

func defaultHistoryCacheDir() (string, error) {
	root, err := os.UserCacheDir()
	if err != nil {
		return "", fmt.Errorf("locate user cache directory: %w", err)
	}
	app := "dg"
	if runtime.GOOS == "darwin" {
		app = "org.coxley.dg"
	}
	return filepath.Join(root, app, "history"), nil
}

func historyCacheKey(path string) (normalized, key string, err error) {
	if path == "" {
		return "", "", errors.New("history path must not be empty")
	}
	normalized, err = filepath.Abs(path)
	if err != nil {
		return "", "", fmt.Errorf("resolve history path: %w", err)
	}
	normalized = filepath.Clean(normalized)
	if runtime.GOOS == "windows" {
		normalized = strings.ToLower(normalized)
	}
	sum := sha256.Sum256([]byte(normalized))
	return normalized, hex.EncodeToString(sum[:]), nil
}

type cacheWrite struct {
	generation uint64
	store      HistoryStore
	key        string
	data       []byte
}

type historyCacheFile struct {
	Version     uint32              `json:"version"`
	SavedDigest string              `json:"saved_digest"`
	Saved       historyCacheLayout  `json:"saved"`
	Entries     []historyCacheEntry `json:"entries"`
	SavedCursor int                 `json:"saved_cursor"`
}

type historyCacheLayout struct {
	Nodes   []historyCacheNode `json:"nodes"`
	Ports   []historyCachePort `json:"ports"`
	Edges   []historyCacheEdge `json:"edges"`
	Padding Padding            `json:"padding"`
	Router  Router             `json:"router"`
}

type historyCacheNode struct {
	Live   bool     `json:"live"`
	Label  string   `json:"label,omitempty"`
	Ports  []uint32 `json:"ports,omitempty"`
	Origin Point    `json:"origin"`
}

type historyCachePort struct {
	Live   bool    `json:"live"`
	Node   uint32  `json:"node"`
	Side   string  `json:"side,omitempty"`
	Offset float32 `json:"offset"`
}

type historyCacheEdge struct {
	Live  bool   `json:"live"`
	PortA uint32 `json:"port_a"`
	PortB uint32 `json:"port_b"`
}

type historyCacheEntry struct {
	Changes []historyCacheChange `json:"changes"`
}

type historyCacheChange struct {
	Kind        historyKind       `json:"kind"`
	ID          uint32            `json:"id"`
	BeforePoint Point             `json:"before_point"`
	AfterPoint  Point             `json:"after_point"`
	BeforeLabel string            `json:"before_label,omitempty"`
	AfterLabel  string            `json:"after_label,omitempty"`
	BeforeEdge  historyCacheEdge  `json:"before_edge"`
	AfterEdge   historyCacheEdge  `json:"after_edge"`
	Node        historyCacheHNode `json:"node"`
}

type historyCacheHNode struct {
	ID     uint32              `json:"id"`
	Label  string              `json:"label,omitempty"`
	Origin Point               `json:"origin"`
	Ports  []historyCacheHPort `json:"ports,omitempty"`
	Edges  []historyCacheHEdge `json:"edges,omitempty"`
}

type historyCacheHPort struct {
	ID     uint32  `json:"id"`
	Node   uint32  `json:"node"`
	Side   string  `json:"side"`
	Offset float32 `json:"offset"`
}

type historyCacheHEdge struct {
	ID    uint32 `json:"id"`
	PortA uint32 `json:"port_a"`
	PortB uint32 `json:"port_b"`
}

func (h *History) marshalCache() ([]byte, error) {
	digest, err := semanticHistoryDigest(h.savedState)
	if err != nil {
		return nil, err
	}
	cache := historyCacheFile{
		Version:     historyCacheVersion,
		SavedDigest: digest,
		Saved:       cacheLayout(h.savedState),
		Entries:     make([]historyCacheEntry, len(h.entries)),
		SavedCursor: h.savedCursor,
	}
	for i, entry := range h.entries {
		cache.Entries[i].Changes = make([]historyCacheChange, len(entry.changes))
		for j, change := range entry.changes {
			cache.Entries[i].Changes[j] = cacheChange(change)
		}
	}
	data, err := json.Marshal(cache)
	if err != nil {
		return nil, fmt.Errorf("encode history cache: %w", err)
	}
	return data, nil
}

func compressHistoryCache(data []byte) ([]byte, error) {
	var compressed bytes.Buffer
	writer := gzip.NewWriter(&compressed)
	if _, err := writer.Write(data); err != nil {
		return nil, errors.Join(
			fmt.Errorf("compress history cache: %w", err),
			writer.Close(),
		)
	}
	if err := writer.Close(); err != nil {
		return nil, fmt.Errorf("finish history cache compression: %w", err)
	}
	return compressed.Bytes(), nil
}

func decodeHistoryCache(data []byte) (historyCacheFile, bool) {
	source := io.Reader(bytes.NewReader(data))
	var compressed *gzip.Reader
	if len(data) >= 2 && data[0] == 0x1f && data[1] == 0x8b {
		var err error
		compressed, err = gzip.NewReader(source)
		if err != nil {
			return historyCacheFile{}, false
		}
		source = compressed
	}

	cache, ok := decodeHistoryCacheJSON(source)
	if compressed != nil {
		if err := compressed.Close(); err != nil {
			return historyCacheFile{}, false
		}
	}
	return cache, ok
}

func decodeHistoryCacheJSON(source io.Reader) (historyCacheFile, bool) {
	decoder := json.NewDecoder(source)
	decoder.DisallowUnknownFields()
	var cache historyCacheFile
	if err := decoder.Decode(&cache); err != nil || cache.Version != historyCacheVersion {
		return historyCacheFile{}, false
	}
	var trailing json.RawMessage
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		return historyCacheFile{}, false
	}
	return cache, true
}

func cacheLayout(state layoutHistoryState) historyCacheLayout {
	cache := historyCacheLayout{
		Nodes:   make([]historyCacheNode, len(state.graph.Nodes)),
		Ports:   make([]historyCachePort, len(state.graph.Ports)),
		Edges:   make([]historyCacheEdge, len(state.graph.Edges)),
		Padding: state.padding,
		Router:  state.router,
	}
	for i, node := range state.graph.Nodes {
		if !state.graph.NodeExists(uint32(i)) {
			continue
		}
		cache.Nodes[i] = historyCacheNode{
			Live:   true,
			Label:  node.Label,
			Ports:  slices.Clone(node.Ports),
			Origin: state.origins[i],
		}
	}
	for i, port := range state.graph.Ports {
		if !state.graph.PortExists(uint32(i)) {
			continue
		}
		cache.Ports[i] = historyCachePort{
			Live:   true,
			Node:   port.Node,
			Side:   port.Side.String(),
			Offset: port.Offset,
		}
	}
	for i, edge := range state.graph.Edges {
		if state.graph.EdgeExists(uint32(i)) {
			cache.Edges[i] = cacheEdge(edge)
		}
	}
	return cache
}

func (c historyCacheLayout) layoutState() (layoutHistoryState, bool) {
	state := layoutHistoryState{
		graph: ir.Graph{
			Nodes: make([]ir.Node, len(c.Nodes)),
			Ports: make([]ir.Port, len(c.Ports)),
			Edges: make([]ir.Edge, len(c.Edges)),
		},
		origins: make([]Point, len(c.Nodes)),
		padding: c.Padding,
		router:  c.Router,
	}
	for i, node := range c.Nodes {
		if node.Live {
			state.graph.Nodes[i] = ir.Node{
				Label: node.Label,
				Ports: slices.Clone(node.Ports),
			}
			state.origins[i] = node.Origin
		}
	}
	for i, port := range c.Ports {
		if !port.Live {
			state.graph.Ports[i] = deletedHistoryPort()
			continue
		}
		side, ok := historySide(port.Side)
		if !ok {
			return layoutHistoryState{}, false
		}
		state.graph.Ports[i] = ir.Port{
			Node:   port.Node,
			Side:   side,
			Offset: port.Offset,
		}
	}
	for i, edge := range c.Edges {
		if edge.Live {
			state.graph.Edges[i] = ir.Edge{PortA: edge.PortA, PortB: edge.PortB}
		}
	}
	state.graph = state.graph.Clone()
	if err := state.graph.Validate(); err != nil {
		return layoutHistoryState{}, false
	}
	return state, true
}

func deletedHistoryPort() ir.Port {
	return ir.Port{Node: math.MaxUint32}
}

func cacheChange(change historyChange) historyCacheChange {
	return historyCacheChange{
		Kind:        change.kind,
		ID:          change.id,
		BeforePoint: change.beforePoint,
		AfterPoint:  change.afterPoint,
		BeforeLabel: change.beforeLabel,
		AfterLabel:  change.afterLabel,
		BeforeEdge:  cacheEdge(change.beforeEdge),
		AfterEdge:   cacheEdge(change.afterEdge),
		Node:        cacheHistoryNode(change.node),
	}
}

func cacheEdge(edge ir.Edge) historyCacheEdge {
	return historyCacheEdge{
		Live:  !edge.Empty(),
		PortA: edge.PortA,
		PortB: edge.PortB,
	}
}

func cacheHistoryNode(node historyNode) historyCacheHNode {
	cached := historyCacheHNode{
		ID:     node.ID,
		Label:  node.Label,
		Origin: node.Origin,
		Ports:  make([]historyCacheHPort, len(node.Ports)),
		Edges:  make([]historyCacheHEdge, len(node.Edges)),
	}
	for i, port := range node.Ports {
		cached.Ports[i] = historyCacheHPort{
			ID:     port.ID,
			Node:   port.Port.Node,
			Side:   port.Port.Side.String(),
			Offset: port.Port.Offset,
		}
	}
	for i, edge := range node.Edges {
		cached.Edges[i] = historyCacheHEdge{
			ID:    edge.ID,
			PortA: edge.Edge.PortA,
			PortB: edge.Edge.PortB,
		}
	}
	return cached
}

func (c historyCacheFile) historyEntries() ([]historyEntry, bool) {
	entries := make([]historyEntry, len(c.Entries))
	for i, cached := range c.Entries {
		entries[i].changes = make([]historyChange, len(cached.Changes))
		for j, change := range cached.Changes {
			decoded, ok := change.historyChange()
			if !ok {
				return nil, false
			}
			entries[i].changes[j] = decoded
		}
	}
	return entries, true
}

func (c historyCacheChange) historyChange() (historyChange, bool) {
	if c.Kind < historyCreateNode || c.Kind > historyReconnectEdge {
		return historyChange{}, false
	}
	node, ok := c.Node.historyNode()
	if !ok {
		return historyChange{}, false
	}
	return historyChange{
		kind:        c.Kind,
		id:          c.ID,
		beforePoint: c.BeforePoint,
		afterPoint:  c.AfterPoint,
		beforeLabel: c.BeforeLabel,
		afterLabel:  c.AfterLabel,
		beforeEdge:  ir.Edge{PortA: c.BeforeEdge.PortA, PortB: c.BeforeEdge.PortB},
		afterEdge:   ir.Edge{PortA: c.AfterEdge.PortA, PortB: c.AfterEdge.PortB},
		node:        node,
	}, true
}

func (c historyCacheHNode) historyNode() (historyNode, bool) {
	node := historyNode{
		ID:     c.ID,
		Label:  c.Label,
		Origin: c.Origin,
		Ports:  make([]historyPort, len(c.Ports)),
		Edges:  make([]historyEdge, len(c.Edges)),
	}
	for i, port := range c.Ports {
		side, ok := historySide(port.Side)
		if !ok {
			return historyNode{}, false
		}
		node.Ports[i] = historyPort{
			ID: port.ID,
			Port: ir.Port{
				Node:   port.Node,
				Side:   side,
				Offset: port.Offset,
			},
		}
	}
	for i, edge := range c.Edges {
		node.Edges[i] = historyEdge{
			ID:   edge.ID,
			Edge: ir.Edge{PortA: edge.PortA, PortB: edge.PortB},
		}
	}
	return node, true
}

func historySide(value string) (ir.Side, bool) {
	switch value {
	case ir.Top.String():
		return ir.Top, true
	case ir.RightSide.String():
		return ir.RightSide, true
	case ir.Bottom.String():
		return ir.Bottom, true
	case ir.LeftSide.String():
		return ir.LeftSide, true
	default:
		return ir.Side{}, false
	}
}

type semanticHistoryState struct {
	Nodes   []semanticHistoryNode `json:"nodes"`
	Ports   []semanticHistoryPort `json:"ports"`
	Edges   []semanticHistoryEdge `json:"edges"`
	Padding Padding               `json:"padding"`
	Router  Router                `json:"router"`
}

type semanticHistoryNode struct {
	Label  string   `json:"label"`
	Origin Point    `json:"origin"`
	Ports  []uint32 `json:"ports"`
}

type semanticHistoryPort struct {
	Side   string  `json:"side"`
	Offset float32 `json:"offset"`
}

type semanticHistoryEdge struct {
	PortA uint32 `json:"port_a"`
	PortB uint32 `json:"port_b"`
}

func semanticHistoryDigest(state layoutHistoryState) (string, error) {
	semantic := semanticHistoryState{
		Padding: state.padding,
		Router:  state.router,
		Nodes:   make([]semanticHistoryNode, 0, len(state.graph.Nodes)),
		Ports:   make([]semanticHistoryPort, 0, len(state.graph.Ports)),
		Edges:   make([]semanticHistoryEdge, 0, len(state.graph.Edges)),
	}
	portIDs := make([]uint32, len(state.graph.Ports))
	for nodeID := range state.graph.Nodes {
		if !state.graph.NodeExists(uint32(nodeID)) {
			continue
		}
		source := state.graph.Nodes[nodeID]
		node := semanticHistoryNode{
			Label:  source.Label,
			Origin: state.origins[nodeID],
			Ports:  make([]uint32, 0, len(source.Ports)),
		}
		for _, portID := range source.Ports {
			port := state.graph.Ports[portID]
			portIDs[portID] = uint32(len(semantic.Ports))
			node.Ports = append(node.Ports, portIDs[portID])
			semantic.Ports = append(semantic.Ports, semanticHistoryPort{
				Side:   port.Side.String(),
				Offset: port.Offset,
			})
		}
		semantic.Nodes = append(semantic.Nodes, node)
	}
	for edgeID := range state.graph.Edges {
		if !state.graph.EdgeExists(uint32(edgeID)) {
			continue
		}
		edge := state.graph.Edges[edgeID]
		semantic.Edges = append(semantic.Edges, semanticHistoryEdge{
			PortA: portIDs[edge.PortA],
			PortB: portIDs[edge.PortB],
		})
	}
	data, err := json.Marshal(semantic)
	if err != nil {
		return "", fmt.Errorf("hash history state: %w", err)
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:]), nil
}

var _ HistoryStore = directoryHistoryStore{}

type historyCacheFields struct {
	cacheDir         string
	cacheStore       HistoryStore
	cacheDelay       time.Duration
	customCacheDir   bool
	customStore      bool
	cachePath        string
	cacheKey         string
	savedState       layoutHistoryState
	savedCursor      int
	cacheBranchValid bool

	cacheMu         sync.Mutex
	cacheWriteMu    sync.Mutex
	cacheTimer      *time.Timer
	cacheGeneration uint64
	pendingCache    cacheWrite
	cacheErr        error
}
